sudo: false
language: node_js
node_js:
  - iojs-v3
after_success:
  - npm run report-cov
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    # d2l-travis-deploy: 9b23......dbcb
    secure: GTm8uI3LPRkEYPRdnTECnOOBEp5MH04dH5nzf4lFfi3JTkNAgBaT4jruAaAmjW7uhiAZhwnK6c9DhTiAVPVrZ+xRuVO4F42GCdmDt6AUclePhRJLNQgZWscWudYiusY0nmzRdWkHG24jyHIGQuomL5S7Tj7xGAyMWhdOud4O8wE+c4lj7V1qNtc7noR3ql5TqhrVNN0yYsW/HB2B3JIYRmCZhBLeOQWZZZDxD4z4xOUCxCGEtRMfKiEzwXCt3a/wNTjsXAX2e03Cs8Ib+8NA78SPhqeTmN8mbIGtIZCyOzKAfYkb6wrks2WsmI0IaVP7BEDRt9fjT3OU1nSkSUrYymPvsvMcJeDnJmk3Qvx7Y0DKctUvF3PLW5xEAbj46Lvy1n67BKhmtNAd3oIK70DnQZjDkqHJ57RLBRgHHP8eNXgLc3hDfPML1wBjjWgtbuU8+dTFIizSNoCPGZRc7E/UFQElE6tB9LtNsk5qR2ejYMmq6A+96PxZHAS/1A/87o9fLP3YDKkedylCttgxSFsf5tFDxfwD4y9+udTDiUejg94YBYV7v9CvBsBCGPKym/Gihn/Q5/h+Ll0onLOr+NH2c9SKLIOoYenCBsWcJ6htzt6r6/65MRDFgTYykSjJXAr5gsRTFxSlTDxtKPYx1OKbTONFMDu5zea7k7klBJGzKmw=
  on:
    tags: true
    repo: Brightspace/node-env-or
